[workspace]
members = [
  "asena",
  "asena-ast",
  "asena-derive",
  "asena-highlight",
  "asena-format",
  "asena-grammar",
  "asena-interner",
  "asena-leaf",
  "asena-lexer",
  "asena-parser",
  "asena-typer",
  "asena-prec",
  "asena-coverage",
  "asena-query",
  "asena-report",
  "asena-span",
]
