
[package]
edition = "2021"
name = "asena-drop-bomb"
version = "0.1.0"

[dependencies]
asena-span = {path = "../asena-span"}

colored = "2"
once_cell = "1.18.0"

fxhash = {workspace = true}
im = {workspace = true}
itertools = {workspace = true}
