
[package]
edition = "2021"
name = "asena-ast"
version = "0.1.0"

[dependencies]
asena-derive = {path = "../asena-derive"}
asena-leaf = {path = "../asena-leaf"}
asena-report = {path = "../asena-report"}
asena-span = {path = "../asena-span"}
im = "15.1.0"
thiserror = "1.0.40"
