[package]
edition = "2021"
name = "asena-driver"
version = "0.1.0"

[dependencies]
asena-driver-derive = {path = "../asena-driver-derive"}
colored = "2"
fxhash = "0.2.1"
im = "15.1.0"
itertools = "0.10.5"
